"""auth workspace realtime schema

Revision ID: 21842b040a52
Revises: 20260918_0001
Create Date: 2026-09-18 22:56:17.921260
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "21842b040a52"
down_revision: str | None = "20260918_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "labs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("checklist_version", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug", "checklist_version"),
    )
    op.create_index(op.f("ix_labs_slug"), "labs", ["slug"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("student_code", sa.String(length=40), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("short_name", sa.String(length=60), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column("class_scope_id", sa.String(length=80), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_class_scope_id"), "users", ["class_scope_id"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_index(op.f("ix_users_student_code"), "users", ["student_code"], unique=True)
    op.create_table(
        "auth_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_auth_sessions_expires_at"), "auth_sessions", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_auth_sessions_token_hash"), "auth_sessions", ["token_hash"], unique=True
    )
    op.create_index(op.f("ix_auth_sessions_user_id"), "auth_sessions", ["user_id"], unique=False)
    op.create_table(
        "canonical_tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("lab_id", sa.Uuid(), nullable=False),
        sa.Column("task_key", sa.String(length=100), nullable=False),
        sa.Column("checkpoint_id", sa.String(length=100), nullable=False),
        sa.Column("task_order", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=60), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("deliverable", sa.String(length=500), nullable=False),
        sa.Column("completion_criteria", sa.JSON(), nullable=False),
        sa.Column("required_skills", sa.JSON(), nullable=False),
        sa.Column("depends_on", sa.JSON(), nullable=False),
        sa.Column("reference_ids", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["lab_id"], ["labs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lab_id", "task_key"),
    )
    op.create_index(op.f("ix_canonical_tasks_lab_id"), "canonical_tasks", ["lab_id"], unique=False)
    op.create_table(
        "groups",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("lab_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("leader_id", sa.Uuid(), nullable=False),
        sa.Column("class_scope_id", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("last_check_in_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lab_id"],
            ["labs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["leader_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_groups_class_scope_id"), "groups", ["class_scope_id"], unique=False)
    op.create_index(op.f("ix_groups_code"), "groups", ["code"], unique=True)
    op.create_index(op.f("ix_groups_lab_id"), "groups", ["lab_id"], unique=False)
    op.create_index(op.f("ix_groups_leader_id"), "groups", ["leader_id"], unique=False)
    op.create_table(
        "realtime_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("scope_type", sa.String(length=20), nullable=False),
        sa.Column("scope_id", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.String(length=100), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("actor_role", sa.String(length=20), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entity_id", "version"),
    )
    op.create_index(
        op.f("ix_realtime_events_entity_id"), "realtime_events", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_realtime_events_event_type"), "realtime_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_realtime_events_occurred_at"), "realtime_events", ["occurred_at"], unique=False
    )
    op.create_index(
        op.f("ix_realtime_events_scope_id"), "realtime_events", ["scope_id"], unique=False
    )
    op.create_index(
        op.f("ix_realtime_events_scope_type"), "realtime_events", ["scope_type"], unique=False
    )
    op.create_table(
        "group_members",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("membership_role", sa.String(length=20), nullable=False),
        sa.Column("invitation_status", sa.String(length=20), nullable=False),
        sa.Column("profile_status", sa.String(length=20), nullable=False),
        sa.Column("invited_by", sa.Uuid(), nullable=False),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["invited_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id", "user_id"),
    )
    op.create_index(op.f("ix_group_members_group_id"), "group_members", ["group_id"], unique=False)
    op.create_index(
        op.f("ix_group_members_invitation_status"),
        "group_members",
        ["invitation_status"],
        unique=False,
    )
    op.create_index(op.f("ix_group_members_user_id"), "group_members", ["user_id"], unique=False)
    op.create_table(
        "help_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("sender_id", sa.Uuid(), nullable=False),
        sa.Column("topic", sa.String(length=200), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("urgent", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("resolved_by", sa.Uuid(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["resolved_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_help_requests_group_id"), "help_requests", ["group_id"], unique=False)
    op.create_index(op.f("ix_help_requests_status"), "help_requests", ["status"], unique=False)
    op.create_table(
        "approved_plans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("draft_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("approved_by", sa.Uuid(), nullable=False),
        sa.Column(
            "approved_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["draft_id"],
            ["assignment_drafts.id"],
        ),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("draft_id"),
    )
    op.create_index(
        op.f("ix_approved_plans_group_id"), "approved_plans", ["group_id"], unique=False
    )
    op.create_table(
        "assignment_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("draft_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("proposed_owner_id", sa.Uuid(), nullable=False),
        sa.Column("approved_owner_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("confidence", sa.String(length=20), nullable=False),
        sa.Column("matched_skills", sa.JSON(), nullable=False),
        sa.Column("overridden", sa.Boolean(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approved_owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["draft_id"], ["assignment_drafts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["proposed_owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["canonical_tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("draft_id", "task_id"),
    )
    op.create_index(
        op.f("ix_assignment_items_draft_id"), "assignment_items", ["draft_id"], unique=False
    )
    op.create_index(
        op.f("ix_assignment_items_task_id"), "assignment_items", ["task_id"], unique=False
    )
    op.create_table(
        "help_replies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("help_request_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["help_request_id"], ["help_requests.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_help_replies_help_request_id"), "help_replies", ["help_request_id"], unique=False
    )
    op.create_table(
        "skill_profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("membership_id", sa.Uuid(), nullable=False),
        sa.Column("industry", sa.String(length=100), nullable=True),
        sa.Column("skills", sa.JSON(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["membership_id"], ["group_members.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_skill_profiles_membership_id"), "skill_profiles", ["membership_id"], unique=True
    )
    op.create_table(
        "task_progress",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("blocked_reason", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["plan_id"], ["approved_plans.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["canonical_tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plan_id", "task_id"),
    )
    op.create_index(op.f("ix_task_progress_owner_id"), "task_progress", ["owner_id"], unique=False)
    op.create_index(op.f("ix_task_progress_plan_id"), "task_progress", ["plan_id"], unique=False)
    op.create_index(op.f("ix_task_progress_task_id"), "task_progress", ["task_id"], unique=False)
    op.add_column("assignment_drafts", sa.Column("group_id", sa.Uuid(), nullable=True))
    op.add_column(
        "assignment_drafts", sa.Column("version", sa.Integer(), server_default="1", nullable=False)
    )
    op.add_column(
        "assignment_drafts",
        sa.Column("gaps", sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    )
    op.add_column(
        "assignment_drafts",
        sa.Column("model_meta", sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    )
    op.add_column("assignment_drafts", sa.Column("created_by", sa.Uuid(), nullable=True))
    op.add_column(
        "assignment_drafts",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
    )
    op.alter_column(
        "assignment_drafts", "group_name", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.alter_column(
        "assignment_drafts",
        "status",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=30),
        existing_nullable=False,
    )
    op.alter_column("assignment_drafts", "request_payload", existing_type=sa.JSON(), nullable=True)
    op.alter_column("assignment_drafts", "result_payload", existing_type=sa.JSON(), nullable=True)
    op.create_index(
        op.f("ix_assignment_drafts_group_id"), "assignment_drafts", ["group_id"], unique=False
    )
    op.create_foreign_key(
        "fk_assignment_drafts_group_id_groups",
        "assignment_drafts",
        "groups",
        ["group_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_assignment_drafts_created_by_users",
        "assignment_drafts",
        "users",
        ["created_by"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_assignment_drafts_created_by_users", "assignment_drafts", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_assignment_drafts_group_id_groups", "assignment_drafts", type_="foreignkey"
    )
    op.drop_index(op.f("ix_assignment_drafts_group_id"), table_name="assignment_drafts")
    op.alter_column("assignment_drafts", "result_payload", existing_type=sa.JSON(), nullable=False)
    op.alter_column("assignment_drafts", "request_payload", existing_type=sa.JSON(), nullable=False)
    op.alter_column(
        "assignment_drafts",
        "status",
        existing_type=sa.String(length=30),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.alter_column(
        "assignment_drafts", "group_name", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.drop_column("assignment_drafts", "updated_at")
    op.drop_column("assignment_drafts", "created_by")
    op.drop_column("assignment_drafts", "model_meta")
    op.drop_column("assignment_drafts", "gaps")
    op.drop_column("assignment_drafts", "version")
    op.drop_column("assignment_drafts", "group_id")
    op.drop_index(op.f("ix_task_progress_task_id"), table_name="task_progress")
    op.drop_index(op.f("ix_task_progress_plan_id"), table_name="task_progress")
    op.drop_index(op.f("ix_task_progress_owner_id"), table_name="task_progress")
    op.drop_table("task_progress")
    op.drop_index(op.f("ix_skill_profiles_membership_id"), table_name="skill_profiles")
    op.drop_table("skill_profiles")
    op.drop_index(op.f("ix_help_replies_help_request_id"), table_name="help_replies")
    op.drop_table("help_replies")
    op.drop_index(op.f("ix_assignment_items_task_id"), table_name="assignment_items")
    op.drop_index(op.f("ix_assignment_items_draft_id"), table_name="assignment_items")
    op.drop_table("assignment_items")
    op.drop_index(op.f("ix_approved_plans_group_id"), table_name="approved_plans")
    op.drop_table("approved_plans")
    op.drop_index(op.f("ix_help_requests_status"), table_name="help_requests")
    op.drop_index(op.f("ix_help_requests_group_id"), table_name="help_requests")
    op.drop_table("help_requests")
    op.drop_index(op.f("ix_group_members_user_id"), table_name="group_members")
    op.drop_index(op.f("ix_group_members_invitation_status"), table_name="group_members")
    op.drop_index(op.f("ix_group_members_group_id"), table_name="group_members")
    op.drop_table("group_members")
    op.drop_index(op.f("ix_realtime_events_scope_type"), table_name="realtime_events")
    op.drop_index(op.f("ix_realtime_events_scope_id"), table_name="realtime_events")
    op.drop_index(op.f("ix_realtime_events_occurred_at"), table_name="realtime_events")
    op.drop_index(op.f("ix_realtime_events_event_type"), table_name="realtime_events")
    op.drop_index(op.f("ix_realtime_events_entity_id"), table_name="realtime_events")
    op.drop_table("realtime_events")
    op.drop_index(op.f("ix_groups_leader_id"), table_name="groups")
    op.drop_index(op.f("ix_groups_lab_id"), table_name="groups")
    op.drop_index(op.f("ix_groups_code"), table_name="groups")
    op.drop_index(op.f("ix_groups_class_scope_id"), table_name="groups")
    op.drop_table("groups")
    op.drop_index(op.f("ix_canonical_tasks_lab_id"), table_name="canonical_tasks")
    op.drop_table("canonical_tasks")
    op.drop_index(op.f("ix_auth_sessions_user_id"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_token_hash"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_expires_at"), table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_index(op.f("ix_users_student_code"), table_name="users")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_class_scope_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_labs_slug"), table_name="labs")
    op.drop_table("labs")
    # ### end Alembic commands ###
